version: '3.7'

services:

  postgres:
    image: "postgres:13.2-alpine"
    env_file: 
      - ./postgres.dev.env 
    volumes:
      - postgres-data:/var/lib/postgresql/data/ 
    networks:
      - squash_subnet
    ports:
      - 5432:5432
    restart: unless-stopped

  nest:
    image: "smartitory/squash-nestjs:latest"
    build:
      context: ./back-end
    networks:
      - squash_subnet
    links:
      - "postgres:postgres"
    ports:
      - 3300:3300
    depends_on:
      - postgres
    restart: unless-stopped
    
volumes:
  postgres-data:
  

networks:
  squash_subnet:
    driver: bridge
    external: false