version: '3.7'

services:

  postgres:
    image: "postgres:13.2-alpine"
    volumes:
      - postgres-data:/var/lib/postgresql/data/ 
    networks:
      - subnet
    ports:
      - 5432:5432
    restart: unless-stopped

  nest:
    image: "smartitory/squash-nestjs:latest"
    build:
      context: ./back-end
    networks:
      - subnet
    links:
      - "postgres:postgres"
    ports:
      - 3300:3300
    depends_on:
      - postgres
    restart: unless-stopped
  
  next:
    image: "smartitory/squash-nextjs:latest"
    build:
      context: ./front-end
    networks:
      - subnet
    links:
      - "nest:api"
    ports:
      - 80:3000
    depends_on:
      - postgres
      - nest
    restart: unless-stopped
    
volumes:
  postgres-data:
  

networks:
  subnet:
    driver: bridge
    external: false